In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.integrate import solve_ivp
from scipy.interpolate import interp1d

from sklearn.model_selection import KFold
from random import shuffle

import time
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
%matplotlib qt

In [2]:
import sys
sys.path.append('..')

In [3]:
import neural_ode.NeuralODE

In [4]:
tf.keras.backend.set_floatx('float64')

In [5]:
model = keras.Sequential(
    [
        keras.Input(shape=(2,)),
        layers.Dense(2, name="layer1"),
    ]
)


In [6]:
n_ode = neural_ode.NeuralODE.NeuralODE(model, 2)

In [7]:
t_eval = tf.linspace(0, 10, 50)
t_span = tf.constant([0.0, 10.0], dtype = tf.float64)
y0 = tf.constant([[0.0, 1.0]], dtype = tf.float64)

In [8]:
n_ode.forward_solve(t_eval, y0)

{'t': <tf.Tensor: shape=(99,), dtype=float64, numpy=
 array([ 0.        ,  0.10204082,  0.20408163,  0.30612245,  0.40816327,
         0.51020408,  0.6122449 ,  0.71428571,  0.81632653,  0.91836735,
         1.02040816,  1.12244898,  1.2244898 ,  1.32653061,  1.42857143,
         1.53061224,  1.63265306,  1.73469388,  1.83673469,  1.93877551,
         2.04081633,  2.14285714,  2.24489796,  2.34693878,  2.44897959,
         2.55102041,  2.65306122,  2.75510204,  2.85714286,  2.95918367,
         3.06122449,  3.16326531,  3.26530612,  3.36734694,  3.46938776,
         3.57142857,  3.67346939,  3.7755102 ,  3.87755102,  3.97959184,
         4.08163265,  4.18367347,  4.28571429,  4.3877551 ,  4.48979592,
         4.59183673,  4.69387755,  4.79591837,  4.89795918,  5.        ,
         5.10204082,  5.20408163,  5.30612245,  5.40816327,  5.51020408,
         5.6122449 ,  5.71428571,  5.81632653,  5.91836735,  6.02040816,
         6.12244898,  6.2244898 ,  6.32653061,  6.42857143,  6.53061224

In [9]:
sol, err = n_ode.solver(n_ode.ode_wrap, t_span, y0, step_size=0.2)

In [10]:
sol['y']

<tf.Tensor: shape=(51, 2), dtype=float64, numpy=
array([[ 0.00000000e+00,  1.00000000e+00],
       [ 2.15281787e-01,  7.93722222e-01],
       [ 4.21592638e-01,  6.27122875e-01],
       [ 6.25997917e-01,  4.92136862e-01],
       [ 8.34989729e-01,  3.82268478e-01],
       [ 1.05473042e+00,  2.92275325e-01],
       [ 1.29126810e+00,  2.17914182e-01],
       [ 1.55073296e+00,  1.55736424e-01],
       [ 1.83952185e+00,  1.02923015e-01],
       [ 2.16447767e+00,  5.71510843e-02],
       [ 2.53306968e+00,  1.64856256e-02],
       [ 2.95358001e+00, -2.07088662e-02],
       [ 3.43530204e+00, -5.58410211e-02],
       [ 3.98875562e+00, -9.01528830e-02],
       [ 4.62592489e+00, -1.24770636e-01],
       [ 5.36052417e+00, -1.60748040e-01],
       [ 6.20829844e+00, -1.99104448e-01],
       [ 7.18736494e+00, -2.40859003e-01],
       [ 8.31860376e+00, -2.87062321e-01],
       [ 9.62610579e+00, -3.38826863e-01],
       [ 1.11376880e+01, -3.97357014e-01],
       [ 1.28854869e+01, -4.63979828e-01],
     

In [35]:
solver = EulerMethod()

In [30]:
solver